apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo.fullname" . }}
  labels:
    app: {{ template "echo.name" . }}
    chart: {{ template "echo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "echo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "echo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: {{ .Values.nginx.healthCheck }}
              port: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.nginx.healthCheck }}
              port: 80
          env:
            - name: BACKEND_HOST
              value: {{ .Values.nginx.backendHost | quote }}
            - name: echo
              image: "{{ .Values.echo.image.repository }}:{{  .Values.echo.image.tag }}"
              imagePullPolicy: {{ .Values.echo.image.pullPolicy }}
              ports:
                - containerPort: {{ .Values.echo.httpPort }}
              env:
                - name: HTTP_PORT
                  value: {{ .Values.echo.httpPort | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
